### ISSUE TITLE
get an empty conf file from JUNOS 9.5R3.7

### ISSUE THREAD

**Issue by liumin6688** [ansible-collections/junipernetworks.junos#129]
##### SUMMARY

when I run `show configuration` command on a machine which os is  JUNOS 9.5R3.7, I can get many configurations,
but when I use playbook like below,I get an empty backup file, How Can I get the configurations correctly,or how to find the reason?and there is no error when I run the playbook, `connection: local` is not be supported or `JUNOS 9.5R3.7` is not be supported?
```
---
- hosts: juniper
  connection: local
  tasks:
    - name: Backup current switch config (junos)
      junipernetworks.junos.junos_config:
        backup: yes
      register: backup_junos_location     
    - name: Print response
      debug:
        var: backup_junos_location 
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

junipernetworks.junos.junos_config:

##### ANSIBLE VERSION
```
ansible 2.10.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home1/irteam/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/python3/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.0 (default, Nov 25 2020, 12:19:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

**Comment by rohitthakur2590** [comment]
@liumin6688 could you please provide detailed logs for this, you can enable the persistent logs as following 
```
export ANSIBLE_LOG_PATH=ansiblelogs.log
export ANSIBLE_PERSISTENT_LOG_MESSAGES=TRUE
export ANSIBLE_DEBUG=TRUE
```
