### ISSUE TITLE
junos_netconf suggestion or issue?

### ISSUE THREAD

**Issue by hrv231** [ansible-collections/junipernetworks.junos#152]
##### SUMMARY

Running a simple playbook to enable netconf, by default sends the "set system services netconf ssh port 830".
I would like the module to check on the Idempotency if the device already have a "system services netconf ssh", if it does, then don't do anything.
Also, it could be the reverse, the module could send the "set system services netconf ssh" and compare it to "set system services netconf ssh port 830", and if it is there, don't do anything.

Another Parameter that is not on the module and we would like to have, if possible of course, is the "confirm_commit" option, the same way as the "junos_config" module.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.10.5
  config file = /home/user1/m-ansible/ansible/ansible.cfg
  configured module search path = ["/home/user1/m-ansible/ansible/'/home/user1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules', '/home/user1/m-ansible/ansible/library'"]
  ansible python module location = /home/user1/m-ansible/lib/python3.7/site-packages/ansible
  executable location = /home/user1/m-ansible/bin/ansible
  python version = 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(/home/user1/m-ansible/ansible/ansible.cfg) = 8
DEFAULT_HOST_LIST(/home/user1/m-ansible/ansible/ansible.cfg) = ['/home/user1/m-ansible/ansible/hosts']
DEFAULT_MODULE_PATH(/home/user1/m-ansible/ansible/ansible.cfg) = ["/home/user1/m-ansible/ansible/'/home/user1/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules', '/home/user1/m-ansible/ansible/library'"]
DEFAULT_PRIVATE_KEY_FILE(/home/user1/m-ansible/ansible/ansible.cfg) = /home/user1/.ssh/myotherkey.pem
DEFAULT_REMOTE_USER(/home/user1/m-ansible/ansible/ansible.cfg) = hvargas
DEFAULT_TIMEOUT(/home/user1/m-ansible/ansible/ansible.cfg) = 57
DEPRECATION_WARNINGS(/home/user1/m-ansible/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/home/user1/m-ansible/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/user1/m-ansible/ansible/ansible.cfg) = /home/user1/m-ansible/bin/python3
INVENTORY_ENABLED(/home/user1/m-ansible/ansible/ansible.cfg) = ['yaml', 'netbox', 'host_list', 'ini', 'virtualbox', 'constructed']
PARAMIKO_HOST_KEY_AUTO_ADD(/home/user1/m-ansible/ansible/ansible.cfg) = True
PARAMIKO_LOOK_FOR_KEYS(/home/user1/m-ansible/ansible/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/user1/m-ansible/ansible/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/home/user1/m-ansible/ansible/ansible.cfg) = 68
RETRY_FILES_ENABLED(/home/user1/m-ansible/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Using WSL on Windows 10
PRETTY_NAME="Debian GNU/Linux 10 (buster)"

Juniper device:
--- JUNOS 18.1R3.3 Kernel 32-bit  JNPR-11.0-20180816.8630ec5_buil
Juniper EX3400-24P

##### STEPS TO REPRODUCE

Generally on my team we only use "set system services netconf ssh" so technically if the playbook does not have the "listens_on" or the "netconf_port", it should send only the command "set system services netconf ssh".
If it has the the "listens_on" or "netconf_port" then it should send the command "set system services netconf ssh port 830".

```yaml
  collections:
    - junipernetworks.junos
  gather_facts: no
  vars:
    ansible_connection: network_cli
    ansible_network_os: junos
  tasks:
    - name: ENABLE NETCONF
      junipernetworks.junos.junos_netconf:
        state: present
      register: test
```

##### EXPECTED RESULTS

"set system services netconf ssh" sent to the device with a commit confirmed.

##### ACTUAL RESULTS

```paste below
set system services netconf ssh port 830 is sent to the device.
```

**Comment by hrv231** [comment]
Hi,
I tested this again and it hasn't changed.
Any updates?

**Comment by rohitthakur2590** [comment]
@hrv231  This is not reproducible with current release. Please open new issue if you are still facing this.
