### ISSUE TITLE
Private argument spec validation methods no longer available in Ansible Core 2.11

### ISSUE THREAD

**Issue by samdoran** [ansible-collections/junipernetworks.junos#162]
##### SUMMARY

Argument spec validation has changed in Ansible Core 2.11. The following private calls should be changed to use the public interface:
```
collections/junipernetworks.junos/plugins/modules/junos_user.py
330:        type_checker = module._CHECK_ARGUMENT_TYPES_DISPATCHER[value_type]  # --> ansible.module_utils.common.parameters.DEFAULT_TYPE_VALIDATORS

collections/junipernetworks.junos/plugins/modules/junos_logging.py
309:        module._check_required_if(required_if, param)  # --> ansible.module_utils.common.validation.check_required_if()
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`junipernetworks.junos/plugins/modules/junos_user.py`
`junipernetworks.junos/plugins/modules/junos_logging.py`

##### ANSIBLE VERSION

```paste below
2.11
```

**Comment by rohitthakur2590** [comment]
for This has been taken care here https://github.com/ansible/ansible/blob/5e131a96c086eda58436429a417c8e7cf256602b/lib/ansible/module_utils/basic.py#L532
for logging global it updated
