### ISSUE TITLE
Support for Junos OS Evolved

### ISSUE THREAD

**Issue by sean-freeman** [ansible-collections/junipernetworks.junos#175]
##### SUMMARY

Support for future releases of [Junos OS Evolved](https://www.juniper.net/documentation/us/en/software/junos/evo-overview/topics/concept/evo-overview.html).

Junos Evo runs on Linux instead of FreeBSD.

Issue opened to facilitate discussion on future development of the collection, not to request specific feature.

**Comment by rohitthakur2590** [comment]
If required Let's have new tracker for this.

**Comment by jamess60** [comment]
@rohitthakur2590 Was a new tracker ever created, and if so, please could you provide the link?

Looks like EVO support is still missing.
