### ISSUE TITLE
Add new states to RM

### ISSUE THREAD

**Issue by danielmellado** [ansible-collections/junipernetworks.junos#19]
##### Add gathered state to the following modules

- [x] junos_ospfv2
- [x] junos_vlans
- [x] junos_acls
- [x] junos_acl_interfaces
- [x] junos_static_routes
- [x] junos_interfaces
- [x] junos_l3_interfaces
- [x] junos_l2_interfaces
- [x] junos_lacp
- [x] junos_lacp_interfaces
- [x] junos_lldp_interfaces
- [x] junos_lldp_global
- [x] junos_lag_interfaces

**Comment by trishnaguha** [comment]
Please take care of adding fully qualified collection name in the examples for these modules in the same PRs as well.

**Comment by danielmellado** [comment]
> Please take care of adding fully qualified collection name in the examples for these modules in the same PRs as well.

I'll create another issue for this ;)
