### ISSUE TITLE
connect() got an unexpected keyword argument 'sock'

### ISSUE THREAD

**Issue by maheshdesai314** [ansible-collections/junipernetworks.junos#194]
##### SUMMARY
connect() got an unexpected keyword argument 'sock'

##### ISSUE TYPE
- Bug Report
- Tried to upgrade Ansible 2.8 to 2.10.10 and it broke Juniper module

##### COMPONENT NAME

Juniper.junos

##### ANSIBLE VERSION

```paste below
ansible 2.10.10
```

##### CONFIGURATION

```paste below
DEFAULT_FORKS(/Users/user1/Desktop/test/ansible.cfg) = 25
HOST_KEY_CHECKING(/Users/user1/Desktop/test/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Running on MacOS 10.14.6
Target is Juniper QFX5120-32C

##### STEPS TO REPRODUCE

```yaml
---
- name: Play to run commands on remote devices
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - name: load configure file into device
      junipernetworks.junos.junos_config:
        lines:
        - set system host-name test
```

##### ACTUAL RESULTS

fatal: [device1]: FAILED! => {
    "changed": false,
    "module_stderr": "",
    "module_stdout": "\n{\"failed\": true, \"msg\": \"connect() got an unexpected keyword argument 'sock'\", \"exception\": \"  File \\\"/var/folders/zf/8g1xw5ws0v155v2lzmr8x_wxxs1w7q/T/ansible_junipernetworks.junos.junos_config_payload_5i3vo8t3/ansible_junipernetworks.junos.junos_config_payload.zip/ansible_collections/junipernetworks/junos/plugins/module_utils/network/junos/junos.py\\\", line 115, in get_capabilities\\n    capabilities = Connection(module._socket_path).get_capabilities()\\n  File \\\"/var/folders/zf/8g1xw5ws0v155v2lzmr8x_wxxs1w7q/T/ansible_junipernetworks.junos.junos_config_payload_5i3vo8t3/ansible_junipernetworks.junos.junos_config_payload.zip/ansible/module_utils/connection.py\\\", line 195, in __rpc__\\n    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)\\n\", \"invocation\": {\"module_args\": {\"lines\": [\"set system host-name test\"], \"update\": \"merge\", \"confirm\": 0, \"comment\": \"configured by junos_config\", \"confirm_commit\": false, \"check_commit\": false, \"backup\": false, \"zeroize\": false, \"src\": null, \"src_format\": null, \"replace\": null, \"backup_options\": null, \"rollback\": null, \"provider\": null}}}\n\n{\"failed\": true, \"msg\": \"connect() got an unexpected keyword argument 'sock'\", \"exception\": \"  File \\\"/var/folders/zf/8g1xw5ws0v155v2lzmr8x_wxxs1w7q/T/ansible_junipernetworks.junos.junos_config_payload_5i3vo8t3/ansible_junipernetworks.junos.junos_config_payload.zip/ansible_collections/junipernetworks/junos/plugins/module_utils/network/junos/junos.py\\\", line 115, in get_capabilities\\n    capabilities = Connection(module._socket_path).get_capabilities()\\n  File \\\"/var/folders/zf/8g1xw5ws0v155v2lzmr8x_wxxs1w7q/T/ansible_junipernetworks.junos.junos_config_payload_5i3vo8t3/ansible_junipernetworks.junos.junos_config_payload.zip/ansible/module_utils/connection.py\\\", line 195, in __rpc__\\n    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)\\n\", \"invocation\": {\"module_args\": {\"lines\": [\"set system host-name test\"], \"update\": \"merge\", \"confirm\": 0, \"comment\": \"configured by junos_config\", \"confirm_commit\": false, \"check_commit\": false, \"backup\": false, \"zeroize\": false, \"src\": null, \"src_format\": null, \"replace\": null, \"backup_options\": null, \"rollback\": null, \"provider\": null}}}\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```paste below

```

**Comment by rabin-io** [comment]
@maheshdesai314 , Just a work around i found,

Edit the META file for the package `junos_eznc` to allow higher version of ncclient (0.6.12 at the moment) and update the packages. That fixed this issue for me.

**Comment by dverbroekkenexnl** [comment]
After some more troubleshooting this is what I found to work with python3 (3.7 and 3.8 tested).
The ansible-galaxy modules and the pip ansible, nccclient, paramiko and pynetbox seem to be the most relevant.
Your milage may vary.

Dependencies (june 2021) :

In user account (not root!) :
$ ansible-galaxy collection list              

# .ansible/collections/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 2.1.0  
ansible.utils     2.2.0  
netbox.netbox     3.1.1  

$ pip list
Package          Version
---------------- -------------
ansible          3.4.0
ansible-base     2.10.10
asn1crypto       0.24.0
bcrypt           3.2.0
certifi          2018.8.24
cffi             1.14.5
chardet          3.0.4
cryptography     3.4.7
entrypoints      0.3
httplib2         0.11.3
idna             2.6
Jinja2           3.0.1
keyring          17.1.1
keyrings.alt     3.1.1
lxml             4.6.3
MarkupSafe       2.0.1
ncclient         0.6.12		
packaging        20.9
paramiko         2.7.2		
pip              21.1.2
pycparser        2.20
pycrypto         2.6.1
pycurl           7.43.0.2
PyGObject        3.30.4
PyNaCl           1.4.0
pynetbox         6.1.2		
pyparsing        2.4.7
PySimpleSOAP     1.16.2
python-apt       1.8.4.3
python-debian    0.1.35
python-debianbts 2.8.2
pyxdg            0.25
PyYAML           5.4.1
reportbug        7.5.3-deb10u1
requests         2.21.0
SecretStorage    2.3.1
setuptools       57.0.0
six              1.16.0
style            1.1.0
update           0.0.1
urllib3          1.24.1
wheel            0.32.3

**Comment by joeslazaro** [comment]
I too was getting the original error message and I can confirm that the suggestion from @dverbroekkenexnl to upgrade ncclient to 0.6.12 solved my problem. The release notes for 0.6.12 includes the statement: "Fix for unintentional breakage of JunOS ExecuteRPC" and I see several commit messages since 0.6.9 which reference junos (https://github.com/ncclient/ncclient/compare/v0.6.9...v0.6.12).

Perhaps this issue should be opened on the https://github.com/Juniper/py-junos-eznc repository instead?

**Comment by rohitthakur2590** [comment]
@maheshdesai314 As this is not reproducible at my end, Could you please share the detailed logs.
You can follow the steps: 
```
export ANSIBLE_LOG_PATH=logs.log
export ANSIBLE_PERSISTENT_LOG_MESSAGES=TRUE
export ANSIBLE_DEBUG=TRUE
```
ansible-playbook -vvv -i inventory <your_playbook>.yaml
