### ISSUE TITLE
Bug in tostring function in module_utils/network/junos/junos.py

### ISSUE THREAD

**Issue by jake2184** [ansible-collections/junipernetworks.junos#225]
##### SUMMARY
Getting an error due to Ansible util function to_text() called with an unexpected keywork argument

Looks due to faulty reworking in commit 2be892f96f1ae49a10bd65c28022c8fcc769d5d8 - 
The ansible [to_text](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/common/text/converters.py) function doesn't take pretty_print as a key work argument, this looks like an error pushing down pretty_print from tostring() args.

```
ansible_collections/junipernetworks/junos/plugins/module_utils/network/junos/junos.py\", line 92, in tostring\nTypeError: to_text() got an unexpected keyword argument 'pretty_print'\n"
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module_utils/network/junos/junos.py

##### ANSIBLE VERSION

```paste below
ansible 2.10.5
  config file = /home/jreynolds/git/dcfabric/ansible.cfg
  configured module search path = ['/home/jreynolds/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/3.8/lib64/python3.8/site-packages/ansible
  executable location = /tmp/3.8/bin/ansible
  python version = 3.8.8 (default, Aug  2 2021, 14:57:02) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
```

##### COLLECTION VERSION

This was introduced between 2.3.0 and 2.4.0, and is still present in 2.5.0.

**Comment by jake2184** [comment]
Any chance this could be merged?

**Comment by woopstar** [comment]
Getting the same error with the following:

```yaml
- name: STAGING - Push config to JunOS
  junos_config:
    src: junos_provision.j2
  tags:
    - junos
```

Using these libs:

```
ansible==4.5.0
ncclient==0.6.12
pynetbox==4.3.0
netaddr==0.8.0
```

**Comment by karstenjakobsen** [comment]
We are experiencing the same issue.

**Comment by woopstar** [comment]
I can confirm fix in PR solves the issue

**Comment by kaon1** [comment]
Is there a workaround for this issue until this bug gets fixed? Should I downgrade the ansible galaxy version?

**Comment by vifino** [comment]
Hey. Chiming in here to say that this is *still* an issue.
#226 fixes the issue. I have to manually patch this bug every time the collection gets updated.

Please, get this merged.

**Comment by aleheux-tc** [comment]
Confirming that this is still an issue almost a year later.

**Comment by rohitthakur2590** [comment]
fixed by: https://github.com/ansible-collections/junipernetworks.junos/pull/306
