### ISSUE TITLE
junos_config: Return values missing

### ISSUE THREAD

**Issue by robertegithub** [ansible-collections/junipernetworks.junos#246]
##### SUMMARY

Most fields of the return values are missing

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

junos_config

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.6] 
  config file = /home/user/scripting/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/scripting/ansible/venv3.9.7/lib/python3.9/site-packages/ansible
  ansible collection location = /home/user/scripting/ansible
  executable location = /home/user/scripting/ansible/venv3.9.7/bin/ansible
  python version = 3.9.7 (default, Sep 10 2021, 00:03:59) [GCC 7.5.0]
  jinja version = 3.0.2
  libyaml = True
```
Same result with
```paste below
ansible 2.10.3
  config file = /path/ansible/ansible.cfg
  configured module search path = ['/path/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /path/Library/Python/3.8/lib/python/site-packages/ansible
  executable location = /path/Library/Python/3.8/bin/ansible
  python version = 3.8.2 (default, Apr  8 2021, 23:19:18) [Clang 12.0.5 (clang-1205.0.22.9)]
```

##### COLLECTION VERSION

```paste below
# /home/user/scripting/ansible/ansible_collections
Collection            Version
--------------------- -------
junipernetworks.junos 2.6.0  
```

##### CONFIGURATION

```paste below
Fri Oct 22 12:27:08 ansible $ ansible-config dump --only-changed
Fri Oct 22 12:27:26 ansible $ 
```

##### OS / ENVIRONMENT

MacOS 11.6
VM Ubuntu Linux 18.04.6

##### STEPS TO REPRODUCE

1) Make a change using junos_config module and register a variable for return values

2) Show return values

```yaml
    - name: Execute the change on the device
      junipernetworks.junos.junos_config:
        lines: "{{ new_configuration }}"
      vars:
        ansible_connection: netconf
      check_mode: "{{ checkmode }}"
      register: results
      when: not checkmode

    ## DEBUG
    - name: Show change module results
      debug:
        msg: "{{ results }}"
    ## END DEBUG
```

##### EXPECTED RESULTS

Additional return values beyond changed and failed, such as:
    diff

    invocation

    msg

    rc

    results

    skipped

    stderr

    stderr_lines

    stdout

    stdout_lines

##### ACTUAL RESULTS

The junos_config task values include, for example:

changed: [some_host] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "backup": false,
            "backup_options": null,
            "check_commit": false,
            "comment": "configured by junos_config",
            "confirm": 0,
            "confirm_commit": false,
            "lines": [
                "delete system ntp server 1.2.3.4",
                "set system ntp server 1.2.3.5",
                "set system ntp server 1.2.3.6"
            ],
            "provider": null,
            "replace": null,
            "rollback": null,
            "src": null,
            "src_format": null,
            "update": "merge",
            "zeroize": false
        }
    }
}

The return values for the registered variable assigned to that task only include:

ok: [some_host] => {
    "msg": {
        "changed": true,
        "failed": false
    }
}

It's missing the majority of standard return values as well as those specific to the junos_config module. 

```paste below
ok: [some_host] => {
    "msg": {
        "changed": true,
        "failed": false
    }
}
```

**Comment by rohitthakur2590** [comment]
@robertegithub  Thank you for providing details regarding this.
`Point 1`: 
This is a correct behavior from junos_config. The standard junos_config output (not for backup) looks like 
```
ok: [11.11.11.11] => {
    "msg": {
        "changed": true,
        "failed": false
    }
}
```
if you run the playbook with verbose output that will also include the invocation part 
```
 "module_args": {
            "backup": false,
            "backup_options": null,
            "check_commit": false,
            "comment": "configured by junos_config",
            "confirm": 0,
            "confirm_commit": false,
            "lines": [
                "set interfaces fxp0 description \"This is Sparta!!!!\""
            ],
            "provider": null,
            "replace": null,
            "rollback": null,
            "src": null,
            "src_format": null,
            "update": "merge",
            "zeroize": false
        }
``` 
which is not the config out but rather what out task executed with.

`Point 2`: 
  for back up task like 
  ```
  - name: Execute the change on the device
      junipernetworks.junos.junos_config:
        lines:
          - set interfaces fxp0 description "This is Sparta!!!!"
        backup: true
  ```
  the result will include as suggested by documentation https://github.com/ansible-collections/junipernetworks.junos/blob/d1ec23efa3c87d831fdf19f79d507b5670aa45f4/plugins/modules/junos_config.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L245
  
  ```
  ok: [192.168.122.75] => {
    "msg": {
        "backup_path": "/home/rthakur/ansible_playbooks/collections/network/juniper/junos/bugs/backup/192.168.12.5_config.2021-12-21@11:17:04",
        "changed": true,
        "date": "2021-12-21",
        "failed": false,
        "filename": "192.168.12.5_config.2021-12-21@11:17:04",
        "shortname": "/home/rthakur/ansible_playbooks/collections/network/juniper/junos/bugs/backup/192.168.12.5_config",
        "time": "11:17:04"
    }
}
  ```

Point 3: 
    If you require more detailed output/result then I would suggest you try our latest resource modules which offer detailed output and you can refer to the `junos_ntp_global` resource module  example here 
https://docs.ansible.com/ansible/latest/collections/junipernetworks/junos/junos_ntp_global_module.html#ansible-collections-junipernetworks-junos-junos-ntp-global-module.
