### ISSUE TITLE
Ansible ping module reports online when a switch is offline

### ISSUE THREAD

**Issue by lazzarello** [ansible-collections/junipernetworks.junos#248]
##### SUMMARY
I have three switches in my Ansible inventory, one is offline. When I run `ansible -i switches -m ping all` the outputs says all three switches are online.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Ansible ping

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.6] 
  config file = /home/lee/src/stand/ansible/ansible.cfg
  configured module search path = ['/home/lee/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lee/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/lee/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/lee/.local/bin/ansible
  python version = 3.9.5 (default, May 11 2021, 08:20:37) [GCC 10.3.0]
  jinja version = 3.0.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
$ ansible-galaxy collection list junipernetworks.junos

# /home/lee/.local/lib/python3.9/site-packages/ansible_collections
Collection            Version
--------------------- -------
junipernetworks.junos 2.6.0  

# /usr/lib/python3/dist-packages/ansible_collections
Collection            Version
--------------------- -------
junipernetworks.junos 1.3.0  

# /home/lee/.ansible/collections/ansible_collections
Collection            Version
--------------------- -------
junipernetworks.junos 2.6.0 
```

##### CONFIGURATION

```paste below
$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/lee/src/stand/ansible/ansible.cfg) = ['/home/lee/src/stand/ansible/test-hosts']
DEFAULT_STDOUT_CALLBACK(/home/lee/src/stand/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/home/lee/src/stand/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

Model: ex3400-48p
Junos: 20.4R3.8
JUNOS OS Kernel 32-bit  [20210618.f43645e_builder_stable_11-204ab]
JUNOS OS libs [20210618.f43645e_builder_stable_11-204ab]
JUNOS OS runtime [20210618.f43645e_builder_stable_11-204ab]
JUNOS OS time zone information [20210618.f43645e_builder_stable_11-204ab]
JUNOS py extensions2 [20210907.154329_builder_junos_204_r3]
JUNOS py extensions [20210907.154329_builder_junos_204_r3]
JUNOS py base2 [20210907.154329_builder_junos_204_r3]
JUNOS py base [20210907.154329_builder_junos_204_r3]
JUNOS OS crypto [20210618.f43645e_builder_stable_11-204ab]
JUNOS OS boot-ve files [20210618.f43645e_builder_stable_11-204ab]
JUNOS network stack and utilities [20210907.154329_builder_junos_204_r3]
JUNOS libs [20210907.154329_builder_junos_204_r3]
JUNOS runtime [20210907.154329_builder_junos_204_r3]
JUNOS na telemetry [20.4R3.8]
JUNOS Web Management Platform Package [20210907.154329_builder_junos_204_r3]
JUNOS ex runtime [20210907.154329_builder_junos_204_r3]
JUNOS probe utility [20210907.154329_builder_junos_204_r3]
JUNOS ex platform support [20210907.154329_builder_junos_204_r3]
JUNOS Openconfig [20.4R3.8]
JUNOS dcp network modules [20210907.154329_builder_junos_204_r3]
JUNOS modules [20210907.154329_builder_junos_204_r3]
JUNOS ex modules [20210907.154329_builder_junos_204_r3]
JUNOS ex libs [20210907.154329_builder_junos_204_r3]
JUNOS ex Data Plane Crypto Support [20210907.154329_builder_junos_204_r3]
JUNOS daemons [20210907.154329_builder_junos_204_r3]
JUNOS SDN Software Suite [20210907.154329_builder_junos_204_r3]
JUNOS Extension Toolkit [20210907.154329_builder_junos_204_r3]
JUNOS Phone-home [20210907.154329_builder_junos_204_r3]
JUNOS Packet Forwarding Engine Support (EX34XX) [20210907.154329_builder_junos_204_r3]
JUNOS jdocs ex [20210907.154329_builder_junos_204_r3]
JUNOS jail runtime [20210618.f43645e_builder_stable_11-204ab]
JUNOS FIPS mode utilities [20210907.154329_builder_junos_204_r3]

##### STEPS TO REPRODUCE

with an offline switch, all have netconf enabled.

```yaml
ansible -i switches -m ping all 
```

##### EXPECTED RESULTS

The offline switches would not return success

##### ACTUAL RESULTS

```paste below
switch-rsc-2-3 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
switch-rsc-2-2 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
switch-rsc-2-1 | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
```

**Comment by rohitthakur2590** [comment]
Thanks for reporting this ,Hi if this issue still persist , feel free to open a new issue with debug logs.
