### ISSUE TITLE
junos_system won't reliably set name_servers

### ISSUE THREAD

**Issue by siemsen** [ansible-collections/junipernetworks.junos#250]
##### SUMMARY
If you supply a list of name_servers, the module may install it in a different order, or if you delete a server from the list, the module may not make any changes.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
junos_system

##### ANSIBLE VERSION
```
ansible 2.10.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/siemsen/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
```

##### COLLECTION VERSION
```
# /usr/share/ansible/collections/ansible_collections
Collection            Version
--------------------- -------
junipernetworks.junos 2.5.0
```

##### CONFIGURATION
```
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = /tmp/ansible
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 14400
COLOR_CHANGED(env: ANSIBLE_COLOR_CHANGED) = bright yellow
COLOR_DEBUG(env: ANSIBLE_COLOR_DEBUG) = bright yellow
COLOR_DEPRECATE(env: ANSIBLE_COLOR_DEPRECATE) = bright purple
COLOR_DIFF_ADD(env: ANSIBLE_COLOR_DIFF_ADD) = bright green
COLOR_DIFF_LINES(env: ANSIBLE_COLOR_DIFF_LINES) = bright cyan
COLOR_DIFF_REMOVE(env: ANSIBLE_COLOR_DIFF_REMOVE) = bright red
COLOR_ERROR(env: ANSIBLE_COLOR_ERROR) = bright red
COLOR_HIGHLIGHT(env: ANSIBLE_COLOR_HIGHLIGHT) = white
COLOR_OK(env: ANSIBLE_COLOR_OK) = bright green
COLOR_SKIP(env: ANSIBLE_COLOR_SKIP) = bright cyan
COLOR_UNREACHABLE(env: ANSIBLE_COLOR_UNREACHABLE) = bright red
COLOR_VERBOSE(env: ANSIBLE_COLOR_VERBOSE) = bright blue
COLOR_WARN(env: ANSIBLE_COLOR_WARN) = bright purple
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts.yml']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = selective
DISPLAY_SKIPPED_HOSTS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INJECT_FACTS_AS_VARS(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_silent
INVENTORY_CACHE_ENABLED(/etc/ansible/ansible.cfg) = True
INVENTORY_CACHE_PLUGIN(/etc/ansible/ansible.cfg) = jsonfile
```

##### OS / ENVIRONMENT
Debian 10.11

##### STEPS TO REPRODUCE
1. Write a playbook that sets the name-servers in a Juniper. (see below)
2. Log in to the Juniper switch.
3. Manually delete any existing name-servers section (in the system section).
4. Run the playbook.
5. In the switch, show the new name-servers section.
When I tried to configure this list:
  - 128.117.64.44
  - 128.117.177.44
  - 128.117.64.45
 The module actually installed this:
 128.117.64.44
 128.117.64.45
 128.117.177.44
Perhaps the module sorted the list before installing it?
When I tried another test - just deleting the last line of the list, the module did nothing.
When I configured the device, and deleted the name-servers section, then ran the playbook, the module installed the list correctly.
```
---
- hosts: test-qfx5110
  vars:
    dns_servers:
      - 128.117.64.44
      - 128.117.177.44 
      - 128.117.64.45
  tasks:
    - name: Setting DNS on NETS devices
      junos_system:
        name_servers: "{{ dns_servers }}"
```

##### EXPECTED RESULTS
I'd like the list in the playbook to be put into the device.

##### ACTUAL RESULTS

```
x
```

**Comment by rohitthakur2590** [comment]
@siemsen  I tried to reproduce this and it is working fine at my end, To know the root cause of this failure at your end could you please share the detailed logs , you can enable detailed debug logs as :
```
export ANSIBLE_LOG_PATH=logs.log
export ANSIBLE_PERSISTENT_LOG_MESSAGES=TRUE
export ANSIBLE_DEBUG=TRUE
``` 
and try running playbook `ansible-playbook -vvv  <playbook>.yaml`
