### ISSUE TITLE
show configuration xxx with no output

### ISSUE THREAD

**Issue by ric79** [ansible-collections/junipernetworks.junos#260]
##### SUMMARY
I'm trying to run "show configuration event-options | no-more" but I get an error because there is nothing configured for "event-options". Another example of the same error is "show configuration system scripts | no-more"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
junipernetworks.junos.junos_command

##### ANSIBLE VERSION
ansible --version
ansible [core 2.11.6]
  config file = None
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/python_envs/yyy-env/lib/python3.9/site-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/xxx/python_envs/yyy-env/bin/ansible
  python version = 3.9.8 (main, Nov 11 2021, 10:03:58) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 3.0.3

##### COLLECTION VERSION
$ ansible-galaxy collection list | grep jun
junipernetworks.junos         2.6.0

##### CONFIGURATION
$ ansible-config dump --only-changed
COLLECTIONS_PATHS(/home/xxx/yyy-prj/yyy/ansible.cfg) = ['/home/xxx/python_envs/${BASE_ANSIBLE_ENV}-ans
DEFAULT_LOG_PATH(/home/xxx/yyy-prj/yyy/ansible.cfg) = /home/xxx/yyy-prj/yyy/logs/l
DEFAULT_ROLES_PATH(/home/xxx/yyy-prj/yyy/ansible.cfg) = ['/home/xxx/python_envs/${BASE_ANSIBLE_ENV}-an
HOST_KEY_CHECKING(/home/xxx/yyy-prj/yyy/ansible.cfg) = False

##### OS / ENVIRONMENT
$ more /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

##### STEPS TO REPRODUCE
Here there is my playbook

```
    - junipernetworks.junos.junos_command:
        commands: show configuration event-options
      register: junos_result
```

I get

```
TASK [] ******************************************************************************************
fatal: [******]: FAILED! => changed=false
  msg: |-
    <rpc-reply message-id="urn:uuid:0c66a577-9530-4c59-90df-d07943eb4c3b">
    </rpc-reply>
```

If I run the command via SSH:
```
> show configuration event-options | no-more

{master}
```

If the router contains the configuration, then the task works nicely

```
TASK [] ******************************************************************************************
ok: [****] => changed=false
  stdout:
  - |-
    commit {
        file config-compare.slax;
    }
    op {
        file alt-save.slax {
            allow-commands document;
        }
        file op-save-config.slax;
        file put-c.slax;
    }
    load-scripts-from-flash;
  stdout_lines: <omitted>
```

Riccardo

**Comment by rohitthakur2590** [comment]
Closing this as we are already tracking it with https://github.com/ansible-collections/junipernetworks.junos/issues/249
