### ISSUE TITLE
Ansible playbook with only one commit

### ISSUE THREAD

**Issue by cardosocristian** [ansible-collections/junipernetworks.junos#271]
##### SUMMARY
When playbooks are executed on Juniper devices, each task is performed a commit on the remote device, depending on the device, it can generate a large CPU consumption.
My idea of a feature, would be to run the tasks in Juniper in config mode and after executing all the tasks commit in fact.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
I understand it would be useful for all Junos modules for ansible.

##### ADDITIONAL INFORMATION
By having a playbook that performs the commit at the end, older equipment does not experience CPU spikes. For example, when executing 5 tasks in sequence on Juniper devices that run PowerPC CPUs, in the case of MX80 routers, this can generate a large CPU consumption and even a router crash, due to having only one core in the RE, another similar case is the EX34xx switches, which have a CPU arm for use in the RE.

**Comment by rohitthakur2590** [comment]
Covering this with https://github.com/ansible-collections/junipernetworks.junos/issues/384
