### ISSUE TITLE
Draft a new Galaxy Release

### ISSUE THREAD

**Issue by josh-silvas** [ansible-collections/junipernetworks.junos#324]
##### SUMMARY
Hi Team,

Is it possible to get a new release cut and published to galaxy? It looks like 3.1.0 was release ~3 months ago and there are some notable features in main that we're looking for (namely functional SNMPv3)

Thanks for all your work on this!

##### ISSUE TYPE
- Release

**Comment by rohitthakur2590** [comment]
@josh-silvas  We have release 4.0.0 one month back. Let me know If you still have concerns.
