### ISSUE TITLE
junos_bgp_global:Integration test failed:the task includes an option with an undefined variable

### ISSUE THREAD

**Issue by komaldesai13** [ansible-collections/junipernetworks.junos#436]
##### SUMMARY
When running junos_bgp_global tests from Controller with EE container,
We get an unexpected error: the task includes an option with an undefined variable
On task [Assert configuration](https://github.com/ansible-collections/junipernetworks.junos/blob/main/tests/integration/targets/junos_bgp_global/tests/netconf/overridden.yaml#L29)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
junos_bgp_global

##### ANSIBLE VERSION
2.15

##### COLLECTION VERSION
18.4R1.8

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE
Run integration junos_bgp_global test, the following task failed.
See below the actual results.

##### EXPECTED RESULTS
The task will pass with not errors.

##### ACTUAL RESULTS
TASK [/usr/share/ansible/collections/ansible_collections/junipernetworks/junos/tests/integration/targets/junos_bgp_global : Assert configuration] ***
04:32:22      task path: /usr/share/ansible/collections/ansible_collections/junipernetworks/junos/tests/integration/targets/junos_bgp_global/tests/netconf/overridden.yaml:29
04:32:22      fatal: [10.0.148.231]: FAILED! => {
04:32:22          "msg": "The task includes an option with an undefined variable. The error was: 'overridden' is undefined. 'overridden' is undefined\\n\\nThe error appears to be in '/usr/share/ansible/collections/ansible_collections/junipernetworks/junos/tests/integration/targets/junos_bgp_global/tests/netconf/overridden.yaml': line 29, column 7, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n\\n    - name: Assert configuration\\n      ^ here\\n"
04:32:22      }

**Comment by rohitthakur2590** [comment]
fixed by: https://github.com/ansible-collections/junipernetworks.junos/pull/434
