### ISSUE TITLE
unnecessary prefix junos_ for plugins while already in a junos_collection

### ISSUE THREAD

**Issue by bmillemathias** [ansible-collections/junipernetworks.junos#78]
##### SUMMARY

is it possible to shorten the plugins name by removing the junos_ prefix ? it bring nothing because they belong to the junos collection anyway and make the plugin name unnecessary long.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
all plugins

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by ganeshrn** [comment]
@bmillemathias We have to keep the `junos_` for modules for backward compatibility as these collections are part of Ansible Community Distribution (ACD) Refer https://groups.google.com/forum/#!topic/ansible-devel/NoYmrpQ3IkU. In the long term, we do have plans to move to use the short name for plugins. 

Currently, the long plugin name (eg. `junipernetworks.junos.junos_config`) is redirected to the short name (eg. `junipernetworks.junos.config`) using [runtime.yml](https://github.com/ansible-collections/junipernetworks.junos/blob/main/meta/runtime.yml) file which is part of the collection. So you can use the short names in your playbook with ansible-base 2.10 release.

**Comment by bmillemathias** [comment]
>  In the long term, we do have plans to move to use the short name for plugins.

great to know, I think user-wide that makes more sense.
Best !

**Comment by rohitthakur2590** [comment]
Hi!

Thanks very much for your interest in Ansible. It sincerely means a lot to us.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

IRC: #ansible on irc.freenode.net
mailing list: https://groups.google.com/forum/#!forum/ansible-project
If you can stop by there, we'd appreciate it. This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC. Thanks!
